[package]
name = "ctm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
tui = "0.19.0"
chrono = "0.4.24"
async-std = "1.12.0"
project-root = "0.2.2"
systemstat = "0.2.3"
